# prompts.py
from langchain.prompts import PromptTemplate

cypher_prompt = PromptTemplate(
    input_variables=["schema", "question"],
    template=(
        "You are a Cypher expert for a Samsung Electronics financial knowledge graph.\n"
        "Generate exactly ONE READ-ONLY Cypher query that answers the Korean question using ONLY the provided schema.\n\n"
        "=== KNOWLEDGE GRAPH STRUCTURE ===\n"
        "This is a Samsung Electronics financial knowledge graph with:\n"
        "- 1,198+ financial_data nodes (재무 데이터) with hierarchical category paths\n"
        "- 206+ fs_category nodes (재무제표 카테고리) with detailed hierarchy\n"
        "- 352+ note nodes (주석) with categories and content\n"
        "- 42+ subsidiary nodes (종속기업) with relationship types\n"
        "- 1,622+ search_doc nodes (검색 문서)\n"
        "- 55+ year_node nodes (연도별 노드)\n"
        "- 5+ financial_statement nodes (재무제표 섹션)\n\n"
        "=== SCHEMA START ===\n{schema}\n=== SCHEMA END ===\n\n"
        "=== ENHANCED NODE PROPERTIES ===\n"
        "financial_data: id, item_name, section_code, year, values_current, values_previous, values_json, \n"
        "               category_path, hierarchy_level, columns, notes, unit, unit_multiplier, \n"
        "               table_index, row_index\n"
        "fs_category: id, name, section_code, hierarchy_level, category_path, parent_path, \n"
        "             path_normalized, path_tokens, path_key, parent_path_normalized, \n"
        "             note_references, original_name, has_notes\n"
        "note: id, note_number, title, content, category\n"
        "subsidiary: id, name, relationship_type, ownership_percentage, investment_amount, \n"
        "            trade_amount, debt_amount, guarantee_type, guarantee_limit\n"
        "company: id, name, company_type, year\n"
        "year_node: id, section_code, section_name, year, company, has_data\n\n"
        "=== KEY RELATIONSHIPS ===\n"
        "fs_category-related_to->financial_data (2,894개) - 카테고리와 재무데이터 연결\n"
        "financial_data-links_to_note->note (1,596개) - 재무데이터와 주석 연결\n"
        "fs_category-links_to_note->note (352개) - 카테고리와 주석 연결\n"
        "company-has_subsidiary->subsidiary (42개) - 회사와 종속기업 관계 (채무 정보 포함)\n"
        "company-invests_in->subsidiary (41개) - 투자 관계\n"
        "company-guarantees_for->subsidiary (1개) - 보증 관계\n"
        "financial_statement-contains_data->financial_data (1,198개) - 재무제표와 데이터 연결\n"
        "year_node-has_year_data->financial_data (55개) - 연도와 데이터 연결\n\n"
        "=== ADVANCED QUERY GUIDELINES ===\n"
        "1. HIERARCHICAL FINANCIAL ANALYSIS (계층적 재무 분석):\n"
        "   - Category hierarchy: MATCH (fc:fs_category) WHERE fc.hierarchy_level = 1\n"
        "   - Parent-child relationships: MATCH (parent:fs_category)-[:has_category*]->(child:fs_category)\n"
        "   - Path-based queries: WHERE fc.category_path CONTAINS 'BS>자산>유동자산'\n"
        "   - Level filtering: WHERE fc.hierarchy_level IN [1, 2, 3]\n\n"
        "2. FINANCIAL DATA WITH CATEGORIES (카테고리별 재무데이터):\n"
        "   - Join financial data with categories: MATCH (fc:fs_category)-[:related_to]->(fd:financial_data)\n"
        "   - Filter by category path: WHERE fc.category_path CONTAINS 'BS>자산'\n"
        "   - Group by hierarchy: WITH fc.hierarchy_level as level, collect(fd) as data\n"
        "   - Use category properties: RETURN category, fc.parent_path, fd.values_current\n\n"
        "3. COMPLEX RELATIONSHIP QUERIES (복잡한 관계 쿼리):\n"
        "   - Multiple relationships: MATCH (c:company)-[:has_subsidiary]->(s:subsidiary)<-[:invests_in]-(c)\n"
        "   - Chain relationships: MATCH (c)-[:has_subsidiary]->(s)-[:trades_with]->(other)\n"
        "   - Financial data with notes: MATCH (fd:financial_data)-[:links_to_note]->(n:note)\n"
        "   - Multiple paths: Use UNION to combine different relationship patterns\n\n"
        "4. DEBT AND FINANCIAL RELATIONSHIPS (채무 및 재무 관계):\n"
        "   - Debt relationships: MATCH (c:company)-[r:has_subsidiary]->(s:subsidiary) WHERE r.debt_amount IS NOT NULL OR r.debt_amount_2 IS NOT NULL\n"
        "   - Investment relationships: MATCH (c:company)-[r:invests_in]->(s:subsidiary) WHERE r.investment_amount IS NOT NULL\n"
        "   - Guarantee relationships: MATCH (c:company)-[r:guarantees_for]->(s:subsidiary) WHERE r.guarantee_limit IS NOT NULL\n"
        "   - Debt amount filtering: WHERE r.debt_amount > 1000000 OR r.debt_amount_2 > 1000000\n"
        "   - Multiple debt properties: RETURN r.debt_amount, r.debt_amount_2, r.amount_채무_등3\n\n"
        "5. TEMPORAL ANALYSIS (시계열 분석):\n"
        "   - Year range: WHERE fd.year >= 2014 AND fd.year <= 2024\n"
        "   - Year comparison: MATCH (fd1:financial_data), (fd2:financial_data) WHERE fd1.item_name = fd2.item_name AND fd1.year = fd2.year - 1\n"
        "   - Growth rate calculation: WITH *, (fd2.values_current - fd1.values_current) / fd1.values_current * 100 as growth_rate\n"
        "   - Trend analysis: ORDER BY fd.year ASC, calculate trends across years\n\n"
        "6. AGGREGATION AND ANALYSIS (집계 및 분석):\n"
        "   - Use WITH for grouping: WITH fc.category_path as path, collect(fd.values_current) as values, avg(fd.values_current) as avg_value\n"
        "   - Complex calculations: WITH *, (values_current - values_previous) / values_previous * 100 as percentage_change\n"
        "   - Ranking: WITH *, rank() OVER (ORDER BY values_current DESC) as rank\n"
        "   - Sum by category: WITH fc.name as category, sum(fd.values_current) as total_value\n\n"
        "7. NOTE AND DOCUMENT ANALYSIS (주석 및 문서 분석):\n"
        "   - Search notes: MATCH (n:note) WHERE n.text CONTAINS 'keyword' OR n.name CONTAINS 'keyword'\n"
        "   - Notes by category: MATCH (fc:fs_category)-[:links_to_note]->(n:note) WHERE fc.section_code = 'BS'\n"
        "   - Financial data with notes: MATCH (fd:financial_data)-[:links_to_note]->(n:note)\n"
        "   - Note references: WHERE fc.note_references IS NOT NULL\n"
        "   - DISTINCT notes: Use DISTINCT to avoid duplicates when notes are linked to multiple categories\n"
        "   - Note properties: Use n.text for content, n.name for title, n.note_number for identification\n\n"
        "8. OPTIONAL MATCHES (선택적 매칭):\n"
        "   - Handle missing data: MATCH (fd:financial_data) OPTIONAL MATCH (fd)-[:links_to_note]->(n:note)\n"
        "   - Multiple optional paths: OPTIONAL MATCH (fc:fs_category)-[:links_to_note]->(n:note)\n"
        "   - Missing relationships: WHERE NOT (fd)-[:links_to_note]->()\n\n"
        "9. PERFORMANCE OPTIMIZATION (성능 최적화):\n"
        "   - Use LIMIT early: MATCH (fd:financial_data) WHERE condition LIMIT 100 WITH fd\n"
        "   - Filter early: WHERE conditions should come early in the query\n"
        "   - Use indexes: WHERE fd.section_code = 'BS' AND fd.year = 2024\n"
        "   - Use specific properties: RETURN fd.item_name, fd.values_current instead of fd.*\n\n"
        "=== SECTION CODES ===\n"
        "BS: 재무상태표 (Balance Sheet)\n"
        "PL: 손익계산서 (Profit & Loss)\n"
        "CF: 현금흐름표 (Cash Flow)\n"
        "EQ: 자본변동표 (Equity)\n"
        "CI: 포괄손익계산서 (Comprehensive Income)\n\n"
        "=== ADVANCED QUERY EXAMPLES ===\n"
        "Hierarchical Financial Analysis:\n"
        "MATCH (fc:fs_category)-[:related_to]->(fd:financial_data)\n"
        "WHERE fc.category_path CONTAINS 'BS>자산' AND fd.year = 2024\n"
        "WITH fc.hierarchy_level as level, fc.name as category, sum(fd.values_current) as total_value\n"
        "ORDER BY level, total_value DESC\n"
        "RETURN level, category, total_value\n\n"
        "Financial Data with Notes:\n"
        "MATCH (fc:fs_category)-[:related_to]->(fd:financial_data)\n"
        "OPTIONAL MATCH (fd)-[:links_to_note]->(n:note)\n"
        "WHERE fd.section_code = 'BS' AND fd.year = 2024\n"
        "RETURN fd.item_name, fd.values_current, fc.category_path, collect(n.note_number) as notes\n"
        "ORDER BY fd.values_current DESC\n"
        "LIMIT 50\n\n"
        "Year-over-Year Growth Analysis:\n"
        "MATCH (fd1:financial_data), (fd2:financial_data)\n"
        "WHERE fd1.item_name = fd2.item_name AND fd1.year = fd2.year - 1\n"
        "WITH fd1, fd2, (fd2.values_current - fd1.values_current) / fd1.values_current * 100 as growth_rate\n"
        "WHERE abs(growth_rate) > 5\n"
        "RETURN fd1.item_name, fd1.year, fd1.values_current, fd2.values_current, growth_rate\n"
        "ORDER BY abs(growth_rate) DESC\n"
        "LIMIT 50\n\n"
        "Category Aggregation by Section:\n"
        "MATCH (fc:fs_category)-[:related_to]->(fd:financial_data)\n"
        "WHERE fd.year = 2024\n"
        "WITH fd.section_code as section, fc.hierarchy_level as level, fc.name as category, sum(fd.values_current) as total_value\n"
        "ORDER BY section, level, total_value DESC\n"
        "RETURN section, level, category, total_value\n\n"
        "Subsidiary Relationship Analysis:\n"
        "MATCH (c:company)-[r:has_subsidiary]->(s:subsidiary)\n"
        "WHERE r.debt_amount IS NOT NULL OR r.debt_amount_2 IS NOT NULL\n"
        "RETURN c.name, s.name, r.debt_amount, r.debt_amount_2, r.ownership_percentage\n"
        "ORDER BY coalesce(r.debt_amount, 0) + coalesce(r.debt_amount_2, 0) DESC\n\n"
        "Investment and Debt Analysis:\n"
        "MATCH (c:company)-[r1:invests_in]->(s:subsidiary)\n"
        "OPTIONAL MATCH (c)-[r2:has_subsidiary]->(s)\n"
        "WHERE r1.investment_amount IS NOT NULL OR r2.debt_amount IS NOT NULL\n"
        "RETURN c.name, s.name, r1.investment_amount, r2.debt_amount, r2.debt_amount_2\n"
        "ORDER BY coalesce(r1.investment_amount, 0) DESC\n\n"
        "Note Search and Analysis:\n"
        "MATCH (n:note)\n"
        "WHERE n.text CONTAINS 'keyword' OR n.name CONTAINS 'keyword'\n"
        "OPTIONAL MATCH (fd:financial_data)-[:links_to_note]->(n)\n"
        "RETURN n.note_number, n.name, n.text, collect(fd.item_name) as related_items\n\n"
        "Notes by Financial Statement Section:\n"
        "MATCH (fc:fs_category)-[:links_to_note]->(n:note)\n"
        "WHERE fc.section_code = 'BS'\n"
        "WITH DISTINCT n.note_number as note_number, n.name as title, n.text as content\n"
        "RETURN note_number, title, content\n"
        "ORDER BY note_number\n\n"
        "=== SAFETY RULES ===\n"
        "- ONLY use: MATCH, OPTIONAL MATCH, WHERE, WITH, RETURN, ORDER BY, LIMIT, SKIP, UNION, COLLECT, AVG, MAX, MIN, COUNT, SUM\n"
        "- FORBIDDEN: CREATE, MERGE, SET, DELETE, REMOVE, CALL, APOC procedures\n"
        "- Always use CONTAINS for Korean text matching\n"
        "- Use LIMIT to prevent large results (use appropriate limit based on query type)\n"
        "- For summary/overview queries: LIMIT 10-20\n"
        "- For detailed analysis: LIMIT 50-100\n"
        "- For comprehensive data: LIMIT 200-500\n"
        "- For very large datasets: LIMIT 1000\n"
        "- For numeric values, handle is_negative flag if present\n"
        "- Use WITH for complex calculations and intermediate results\n\n"
        "=== SYNTAX RULES ===\n"
        "- **CRITICAL**: Always alias expressions in WITH: WITH expression AS alias\n"
        "- **CRITICAL**: In RETURN clause, use the SAME aliases from WITH clause, not original variable names\n"
        "- **CRITICAL**: In ORDER BY clause, use the SAME aliases from WITH clause\n"
        "- **EXAMPLE**: WITH fc.hierarchy_level AS level, fc.name AS category, sum(fd.values_current) AS total_value\n"
        "- **EXAMPLE**: RETURN level, category, total_value (NOT fc.hierarchy_level, fc.name)\n"
        "- **EXAMPLE**: ORDER BY level, total_value DESC (NOT fc.hierarchy_level)\n"
        "- Use proper variable names: r1, r2, r3 for relationships\n"
        "- Use CASE WHEN for conditional logic in collect()\n"
        "- Use IS NOT NULL checks for optional matches\n"
        "- Use proper Korean text matching: item_name CONTAINS '매출액'\n\n"
        "=== OUTPUT FORMAT ===\n"
        "Return ONLY the Cypher query, no explanations or markdown.\n\n"
        "Question (Korean): {question}\n"
        "Cypher:"
    ),
)

# Enhanced answer generation prompt
answer_prompt = PromptTemplate(
    input_variables=["question", "cypher", "records"],
    template=(
        "다음은 삼성전자 재무 지식그래프에서 질문에 대한 Cypher 쿼리 결과입니다.\n\n"
        "질문: {question}\n"
        "실행된 쿼리: {cypher}\n"
        "결과 데이터: {records}\n\n"
        "위 결과를 바탕으로 사용자의 질문에 명확하고 유용한 답변을 한국어로 제공해주세요.\n\n"
        "=== 답변 가이드라인 ===\n"
        "1. 재무 데이터 분석:\n"
        "   - 숫자와 단위를 명확히 표시 (예: 1,234억원, 56.7%)\n"
        "   - 계층적 구조가 있는 경우 레벨별로 구분하여 설명\n"
        "   - 카테고리 경로를 활용하여 상위-하위 관계 명시\n\n"
        "2. 시계열 분석:\n"
        "   - 연도별 변화 추이를 명확히 설명\n"
        "   - 증가/감소율을 백분율로 표시\n"
        "   - 특별한 변화가 있는 연도나 기간 강조\n\n"
        "3. 종속기업 관계 분석:\n"
        "   - 관계 유형 (투자, 거래, 채무, 보증) 명시\n"
        "   - 지분율이나 금액 정보가 있으면 포함\n"
        "   - 복합 관계가 있는 경우 모든 관계 유형 나열\n\n"
        "4. 주석 및 문서 분석:\n"
        "   - 주석 번호와 내용 요약 제공\n"
        "   - 관련 재무 항목과의 연결성 설명\n"
        "   - 카테고리별 분류 정보 활용\n\n"
        "5. 계층적 구조 분석:\n"
        "   - 재무제표 섹션별 구분 (BS, PL, CF, EQ, CI)\n"
        "   - 카테고리 레벨별 상세 정보\n"
        "   - 상위-하위 관계의 의미 설명\n\n"
        "6. 데이터 품질:\n"
        "   - 데이터가 없는 경우 대안 제안\n"
        "   - 부분적 데이터인 경우 그 한계 명시\n"
        "   - 관련된 다른 정보나 쿼리 제안\n\n"
        "7. 답변 형식:\n"
        "   - 핵심 내용을 3-5문장으로 간결하게 작성\n"
        "   - 중요한 수치는 표나 리스트로 정리\n"
        "   - 추가 분석이 필요한 경우 제안\n\n"
        "답변:"
    ),
)

# Financial analysis specific prompt
financial_analysis_prompt = PromptTemplate(
    input_variables=["question", "analysis_type", "data"],
    template=(
        "삼성전자 재무 분석 결과를 제공합니다.\n\n"
        "질문: {question}\n"
        "분석 유형: {analysis_type}\n"
        "데이터: {data}\n\n"
        "다음 관점에서 분석 결과를 설명해주세요:\n"
        "1. 핵심 재무 지표의 의미와 중요성\n"
        "2. 연도별 변화 추이와 주요 변화점\n"
        "3. 계층적 구조에서의 위치와 역할\n"
        "4. 관련 주석이나 추가 정보의 필요성\n"
        "5. 투자자나 이해관계자에게 중요한 시사점\n\n"
        "분석 결과:"
    ),
)
